base_config: &BASE_CONFIG
    random_seed: 42
    # log_test_interval: 100

transformer: &TRANSFORMER
    <<: *BASE_CONFIG
    # binary operation
    operation: 'x+y'
    prime: 97
    training_fraction: 0.5
    optimizer: 'adamw'

    # transformer parameters
    num_layers: 2
    dim_model: 128
    num_heads: 4
    batch_size: 512
    learning_rate: 0.001
    weight_decay: 1
    dropout: 0.0
    epochs: 10000

mlp: &MLP
    <<: *BASE_CONFIG
    operation: 'x+y'
    prime: 97
    training_fraction: 0.5
    num_layers: 2
    dim_model: 128
    num_heads: 4
    batch_size: 512
    dropout: 0.0
    epochs: 10000
    learning_rate: 0.001
    weight_decay: 1e-4

LSTM: &LSTM
    <<: *BASE_CONFIG
    # binary operation
    operation: 'x+y'
    prime: 97
    training_fraction: 0.5

    # LSTM parameters
    epochs: 1000